#!/usr/bin/env python
#
# twitter:
# Twitter Iridium flares and ISS flybys above Birmingham
#
# Copyright (c) 2009 Matthew Somerville. http://www.dracos.co.uk/

import codecs
import json
import sys
import arrow
import tweepy
from config import *
dir = sys.path[0] + '/'

def main():
    soon = arrow.utcnow().replace(minutes=30)

    weather = json.load(open(dir + 'weather.json'))
    if not weather: return # Problem with weather file

    weather_desc = weather['summary']

    flares = codecs.open(dir + 'iridium.tsv', encoding='utf-8')
    for row in flares:
        epoch, mag, altitude, azimuth, compass, name = row.strip().split("\t")
        epoch = arrow.get(epoch).to('Europe/London')
        if soon >= epoch and soon < epoch.replace(minutes=5):
            s = u"Iridium flare: magnitude %s at %s, altitude %s, in direction %s (%s), from %s. Weather: %s." % (
                mag, epoch.format('HH:mm:ss'), altitude, azimuth, compass, name, weather_desc
            )
            twitter(s)

    iss = codecs.open(dir + 'iss.tsv', encoding='utf-8')
    for row in iss:
        epoch, mag, start_time, end_time, start_az, end_az, max_time, max_alt, max_az = row.strip().split("\t")
        epoch = arrow.get(epoch).to('Europe/London')
        if soon >= epoch and soon < epoch.replace(minutes=5):
            s = u"ISS pass: magnitude %.1f, %s\u2013%s from %s to %s, maximum altitude %s at %s in %s. Weather: %s." % (
                float(mag), start_time, end_time, start_az, end_az, max_alt, max_time, max_az, weather_desc
            )
            twitter(s)

def twitter(line):
    line = line.encode('utf-8')
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
    return tweepy.API(auth).update_status(line)

main()
