#!/usr/bin/env python
#
# Run hourly to fetch latest weather from forecast.io

import json
import sys
import urllib
from config import FORECASTIO_KEY, LATITUDE, LONGITUDE

weather = json.load(urllib.urlopen('https://api.forecast.io/forecast/%s/%s,%s?units=uk2&exclude=minutely,hourly,daily,alerts,flags' % (FORECASTIO_KEY, LATITUDE, LONGITUDE)))

json.dump(weather['currently'], open(sys.path[0] + '/weather.json', 'w'))
